FROM node:16.13-slim

WORKDIR /frontend

RUN apt-get update && \
    apt-get install -y \
    wget \
    net-tools \
    build-essential

COPY package.json /frontend/
COPY package-lock.json /frontend/

RUN npm ci && \
    npm cache clean --force && \
    npm cache verify

COPY . /frontend/

RUN npm run build
CMD npm run start
