version: "3"

services:
  database:
    image: postgres:14.5-alpine
    container_name: djavue-database
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=djavue
      - POSTGRES_USER=djavue
      - POSTGRES_PASSWORD=djavue
    restart: on-failure
    volumes:
      - data:/var/lib/postgresql/data

  front:
    build:
      context: front/
    image: djavue-front:dev
    container_name: djavue-front
    hostname: djavue-front
    command: npm run dev:disable-mock
    ports:
      - 3000:3000
    volumes:
      - node_modules:/front/node_modules

volumes:
  data:
  node_modules:
