FROM node:16.13-slim

WORKDIR /front

COPY package.json package.json
COPY package-lock.json package-lock.json

RUN npm ci && \
    npm cache clean --force && \
    npm cache verify

COPY . /front

RUN npm run build
CMD npm run start
