FROM node:16.13-slim

WORKDIR /front

RUN apt-get update && \
    apt-get install -y \
    wget \
    net-tools \
    build-essential

COPY package.json /front/
COPY package-lock.json /front/

RUN npm ci && \
    npm cache clean --force && \
    npm cache verify

COPY . /front/

RUN npm run build
CMD npm run start
